spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.h2.console.enabled=false
spring.flyway.enabled=true
