CREATE TABLE app_users (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           email VARCHAR(255) NOT NULL UNIQUE,
                           password_hash VARCHAR(255) NOT NULL
);